'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Wells.Model.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fisico químico	pH	SM 4500 H+ B	UpH
        '''Fisico químico	Conductividad	SM 2510 B REVISION 2011	uS/cm
        '''Fisico químico	Residuos Secos	SM 2540 B	mg/l
        '''Fisico químico	Alcalinidad de Bicarbonato	SM 2320 B	mg/l
        '''Fisico químico	Alcalinidad de Carbonato	SM 2320 B	mg/l
        '''Fisico químico	Cloruros	SM 4500 CL B	mg/l
        '''Fisico químico	Nitratos	SM 4500 NO3-Nitratos Revision 2011	mg/l
        '''Fisico químico	Sulfatos	SM 4500 SO4 E	mg/l
        '''Fisico químico	Calcio	SM 3500 CA D	mg/l
        '''Fisico químico	Magnesio (Mg)	SM 3500 Mg E	mg/l
        '''Fisico químico	 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FLNA() As String
            Get
                Return ResourceManager.GetString("FLNA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Humedad	Humedad	Pérdida de peso a 105ºC	%
        '''pH	pH	EPA 9045 A/C	mg/kg
        '''HTP	DRO	EPA 8015	mg/kg
        '''HTP	GRO	EPA 8015	mg/kg
        '''HTP	MRO	EPA 8015	mg/kg
        '''HTP	Hidrocarburos totales	EPA 8015	mg/kg
        '''HTP	Hidrocarburos totales	TNRCC 1005	mg/kg
        '''HTP	Aceites y grasas	SM 5520 D	mg/kg
        '''&quot;Hidrocarburos
        ''' Fracción alifática&quot;	&gt; C6 - C8	TNRCC 1006	mg/kg
        '''&quot;Hidrocarburos
        ''' Fracción alifática&quot;	&gt; C8 - C10	TNRCC 1006	mg/kg
        '''&quot;Hidrocarburos
        ''' Fracción alifática&quot;	&gt; C10 - C12	TNRCC 1006	mg/kg
        '''&quot;Hidrocarburos
        ''' Fracción alifática&quot;	&gt; C12 - C16	TNRC [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Soil() As String
            Get
                Return ResourceManager.GetString("Soil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fisico químico	pH	SM 4500 H+ B	UpH
        '''Fisico químico	Conductividad	SM 2510 B REVISION 2011	uS/cm
        '''Fisico químico	Residuos Secos	SM 2540 B	mg/l
        '''Fisico químico	Alcalinidad de Bicarbonato	SM 2320 B	mg/l
        '''Fisico químico	Alcalinidad de Carbonato	SM 2320 B	mg/l
        '''Fisico químico	Cloruros	SM 4500 CL B	mg/l
        '''Fisico químico	Nitratos	SM 4500 NO3-Nitratos Revision 2011	mg/l
        '''Fisico químico	Sulfatos	SM 4500 SO4 E	mg/l
        '''Fisico químico	Calcio	SM 3500 CA D	mg/l
        '''Fisico químico	Magnesio (Mg)	SM 3500 Mg E	mg/l
        '''Fisico químico	 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Water() As String
            Get
                Return ResourceManager.GetString("Water", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
