//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wells.YPFModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wells.YPFModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLNA	GRO	EPA 8013	%
        ///FLNA	DRO	EPA 8014	%
        ///FLNA	MRO	EPA 8015	%
        ///FLNA	Benceno	EPA 8260	%
        ///FLNA	Tolueno	EPA 8260	%
        ///FLNA	Etilbenceno	EPA 8260	%
        ///FLNA	Xilenos	EPA 8260	%
        ///FLNA	C6 - C8	TNRCC 1006	%
        ///FLNA	C8 - C10	TNRCC 1006	%
        ///FLNA	C10 - C12	TNRCC 1006	%
        ///FLNA	C12 - C16	TNRCC 1006	%
        ///FLNA	C16 - C21	TNRCC 1006	%
        ///FLNA	C21 - C35	TNRCC 1006	%
        ///FLNA	C17/Pristano	CALCULO	N/A
        ///FLNA	C18/Fitano	CALCULO	N/A
        ///FLNA	Densidad Real	ASTM 1298	g/cm3
        ///FLNA	Viscosidad Dinámica	ASTM 445/65	cP
        ///.
        /// </summary>
        internal static string FLNA {
            get {
                return ResourceManager.GetString("FLNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humedad	Humedad	Pérdida de peso a 105ºC	%
        ///pH	pH	EPA 9045 A/C	mg/Kg
        ///HTP	DRO	EPA 8015	mg/Kg
        ///HTP	GRO	EPA 8015	mg/Kg
        ///HTP	MRO	EPA 8015	mg/Kg
        ///HTP	Hidrocarburos totales (EPA 8015)	EPA 8015	mg/Kg
        ///HTP	Hidrocarburos totales (TNRCC 1005)	TNRCC 1005	mg/Kg
        ///HTP	Aceites y grasas	SM 5520 D	mg/Kg
        ///Hidrocarburos Fracción alifática	&gt; C6 - C8 (F. alifática)	TNRCC 1006	mg/Kg
        ///Hidrocarburos Fracción alifática	&gt; C8 - C10 (F. alifática)	TNRCC 1006	mg/Kg
        ///Hidrocarburos Fracción alifática	&gt; C10 - C12 (F. alifática)	TNRCC 1006 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Soil {
            get {
                return ResourceManager.GetString("Soil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisico químico	pH	SM 4500 H+ B	UpH
        ///Fisico químico	Conductividad	SM 2510 B REVISION 2011	uS/cm
        ///Fisico químico	Residuos Secos	SM 2540 B	mg/l
        ///Fisico químico	Alcalinidad de Bicarbonato	SM 2320 B	mg/l
        ///Fisico químico	Alcalinidad de Carbonato	SM 2320 B	mg/l
        ///Fisico químico	Cloruros	SM 4500 CL B	mg/l
        ///Fisico químico	Nitratos	SM 4500 NO3-Nitratos Revision 2011	mg/l
        ///Fisico químico	Sulfatos	SM 4500 SO4 E	mg/l
        ///Fisico químico	Calcio	SM 3500 CA D	mg/l
        ///Fisico químico	Magnesio (Mg)	SM 3500 Mg E	mg/l
        ///Fisico químico	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
    }
}
