//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wells.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wells.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLNA	GRO	EPA 8013	%
        ///FLNA	DRO	EPA 8014	%
        ///FLNA	MRO	EPA 8015	%
        ///FLNA	Benzene	EPA 8260	%
        ///FLNA	Tolueno	EPA 8260	%
        ///FLNA	Ethylbenzene	EPA 8260	%
        ///FLNA	Xylenes	EPA 8260	%
        ///FLNA	C6_C8	TNRCC 1006	%
        ///FLNA	C8_C10	TNRCC 1006	%
        ///FLNA	C10_C12	TNRCC 1006	%
        ///FLNA	C12_C16	TNRCC 1006	%
        ///FLNA	C16_C21	TNRCC 1006	%
        ///FLNA	C21_C35	TNRCC 1006	%
        ///FLNA	C17_Pristano	CALCULO	N/A
        ///FLNA	C18_Fitano	CALCULO	N/A
        ///FLNA	RealDensity	ASTM 1298	g/cm3
        ///FLNA	DynamicViscosity	ASTM 445/65	cP.
        /// </summary>
        internal static string FLNA {
            get {
                return ResourceManager.GetString("FLNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humedad	Humidity	Pérdida de peso a 105ºC	%
        ///pH	PH	EPA 9045 A/C	mg/Kg
        ///HTP	DRO	EPA 8015	mg/Kg
        ///HTP	GRO	EPA 8015	mg/Kg
        ///HTP	MRO	EPA 8015	mg/Kg
        ///HTP	TotalHydrocarbons_EPA8015	EPA 8015	mg/Kg
        ///HTP	TotalHydrocarbons_TNRCC1005	TNRCC 1005	mg/Kg
        ///HTP	OilsAndFats	SM 5520 D	mg/Kg
        ///Hidrocarburos Fracción alifática	C6_C8Aliphatic	TNRCC 1006	mg/Kg
        ///Hidrocarburos Fracción alifática	C8_C10Aliphatic	TNRCC 1006	mg/Kg
        ///Hidrocarburos Fracción alifática	C10_C12Aliphatic	TNRCC 1006	mg/Kg
        ///Hidrocarburos Fracción alifática	C12_C16 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Soil {
            get {
                return ResourceManager.GetString("Soil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisico químico	PH	SM 4500 H+ B	UpH
        ///Fisico químico	Conductivity	SM 2510 B REVISION 2011	uS/cm
        ///Fisico químico	DryWaste	SM 2540 B	mg/l
        ///Fisico químico	BicarbonateAlkalinity	SM 2320 B	mg/l
        ///Fisico químico	CarbonateAlkalinity	SM 2320 B	mg/l
        ///Fisico químico	Chlorides	SM 4500 CL B	mg/l
        ///Fisico químico	Nitrates	SM 4500 NO3-Nitratos Revision 2011	mg/l
        ///Fisico químico	Sulfates	SM 4500 SO4 E	mg/l
        ///Fisico químico	Calcium	SM 3500 CA D	mg/l
        ///Fisico químico	Magnesium	SM 3500 Mg E	mg/l
        ///Fisico químico	TotalSulfur	SM 4500 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
    }
}
